version: '3'

services:
  web:
    restart: always
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/usr/src
      - ./static:/usr/src/static
      - ./templates:/usr/src/templates
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - ./static:/etc/nginx/html/static
      - ./templates:/etc/nginx/html/templates
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:12.2
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - postgres_data:/usr/local/var/postgres/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

volumes:
    postgres_data: