version: '3'

services:
  web:
    restart: always
    environment: 
      TZ: Asia/Tokyo
    build:
      context: .
    volumes:
      - .:/usr/src
      - ./static:/usr/src/static
      - ./templates:/usr/src/templates
    command: $COMMAND
    ports:
      - 8000:8000
    depends_on:
      - postgres

  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx:/etc/nginx
      - ./static:/etc/nginx/html/static
      - ./templates:/etc/nginx/html/templates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgres:
    restart: always
    image: postgres:12.2
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
