# Generated by Django 3.0.2 on 2020-02-02 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('body', models.TextField(null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新日')),
                ('version', models.IntegerField(default=1, verbose_name='バージョン')),
            ],
            options={
                'db_table': 'novel',
            },
        ),
    ]
