# Generated by Django 3.0.2 on 2020-02-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='version',
            field=models.IntegerField(default=1, verbose_name='バージョン'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
