# Generated by Django 3.0.2 on 2020-02-04 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0002_novel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='version',
        ),
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outline', models.TextField(null=True, verbose_name='本文')),
                ('novel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovelEditor.Novel', verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'novel_info',
            },
        ),
        migrations.CreateModel(
            name='NovelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(verbose_name='作成日')),
                ('novel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovelEditor.Novel', verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'novel_history',
            },
        ),
    ]
