# Generated by Django 3.0.2 on 2020-02-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0003_auto_20200205_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelhistory',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovelEditor.Novel', verbose_name='小説ID'),
        ),
        migrations.AlterField(
            model_name='novelinfo',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovelEditor.Novel', verbose_name='小説ID'),
        ),
    ]
