# Generated by Django 3.0.2 on 2020-02-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0004_auto_20200205_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelinfo',
            name='hero',
            field=models.CharField(max_length=255, null=True, verbose_name='主人公名'),
        ),
        migrations.AddField(
            model_name='novelinfo',
            name='heroine',
            field=models.CharField(max_length=255, null=True, verbose_name='ヒロイン'),
        ),
    ]
