# Generated by Django 3.0.2 on 2020-02-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0005_auto_20200205_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelhistory',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='タイトル'),
        ),
    ]
