# Generated by Django 3.0.4 on 2020-03-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0007_auto_20200321_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='max_revision_id',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='最新バージョン'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='revision_id',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='バージョン'),
        ),
        migrations.AlterField(
            model_name='novelhistory',
            name='revision_id',
            field=models.IntegerField(null=True, verbose_name='バージョン'),
        ),
    ]
