# Generated by Django 3.0.4 on 2020-03-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0009_auto_20200322_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='max_revision_id',
        ),
        migrations.AlterField(
            model_name='novel',
            name='revision_id',
            field=models.IntegerField(null=True, verbose_name='バージョン'),
        ),
        migrations.AlterField(
            model_name='novelhistory',
            name='revision_id',
            field=models.IntegerField(null=True, verbose_name='バージョン'),
        ),
    ]
