# Generated by Django 3.0.4 on 2020-06-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovelEditor', '0010_auto_20200323_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovelInfo',
        ),
    ]
