jobs:
    test:
      docker:
        - image: circleci/python:3.6.4
        - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: NovelHub
      working_directory: .
      steps:
        - checkout
        - run:
            command: 'python manage.py test'
