version: 2.1

# 実行環境の定義
executors:
  test_default:
    working_directory: ~/project
    docker:
    - image: circleci/python:3.7
      environment:
        PYTHONDONTWRITEBYTECODE: 1
        PYTHONUNBUFFERED: 1
        TZ: Asia/Tokyo
    - image: circleci/postgres:12.2
      name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        TZ: Asia/Tokyo

  deploy_default:
    working_directory: ~/project
    docker:
    - image: circleci/python:3.7
      environment:
        PYTHONDONTWRITEBYTECODE: 1
        PYTHONUNBUFFERED: 1
        TZ: Asia/Tokyo

# 実行コマンドの定義
commands:
  pip_install:
    description: "pip install を実行"
    steps:
      - run:
          name: pip install
          command: pip3 install -r requirements.txt --user

# ジョブの定義
jobs:
  build:
    executor: test_default
    steps:
      - checkout
      - pip_install
      - run:
          name: Decode env file
          command: echo $ENV | base64 --decode > .env
      - run:
          name: create necessary folders and files
          command: |
            mkdir postgresql
            mkdir logs
            touch logs/django.log
      - run:
          name: test
          command: python manage.py test --settings config.circleci_test_settings

workflows:
  version: 2.1
  build:
    jobs:
    - build
